---
# tasks file for lazydocker | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and extracting {{ lazydocker_app }} {{ lazydocker_version }}
  unarchive:
    src: "{{ lazydocker_dl_url }}"
    dest: "{{ lazydocker_bin_path }}"
    extra_opts:
      - lazydocker
    remote_src: yes
