---
# tasks file for lazydocker | EL Family

- name: EL Family | Downloading and extracting {{ lazydocker_app }} {{ lazydocker_version }}
  ansible.builtin.unarchive:
    src: "{{ lazydocker_dl_url }}"
    dest: "{{ lazydocker_bin_path }}"
    extra_opts:
      - lazydocker
    remote_src: yes
    owner: "{{ lazydocker_file_owner }}"
    group: "{{ lazydocker_file_group }}"
    mode: "{{ lazydocker_file_mode }}"
